### ISSUE TITLE
can we save images with Default image name insted of Numbers?

### ISSUE THREAD

**Issue by websonder** [ohyicong/Google-Image-Scraper#27]
Can we save image  with default image name insted of imag1, imag2, 
or can we import keywords.txt file for target keywords? like i want to extract  1000 keywords so can i import keywords.txt every keywords in new line mention, is it possible ?

**Comment by fbarretto** [comment]
Hi, I was playing around with this scraper and also wanted to keep original filenames so I've submitted a pull request #28 
Hope it helps you.

Cheers

**Comment by ohyicong** [comment]
@fbarretto thanks for the edit! I have merged the pull request 👍

**Comment by websonder** [comment]
thanks for help, its still showing same name, how i can save with original name?
